// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct ExecRptEndOfStream {
    pub pbu: String,
    pub set_id: u32,
    pub end_report_index: u64,
}

impl BinaryCodec for ExecRptEndOfStream {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.pbu, 8);
        buf.put_u32(self.set_id);
        buf.put_u64(self.end_report_index);
    }

    fn decode(buf: &mut Bytes) -> Option<ExecRptEndOfStream> {
        let pbu = get_char_array(buf, 8)?;
        let set_id = buf.get_u32();
        let end_report_index = buf.get_u64();
        Some(Self {
            pbu,
            set_id,
            end_report_index,
        })
    }
}

#[cfg(test)]
mod exec_rpt_end_of_stream_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_exec_rpt_end_of_stream_codec() {
        let original = ExecRptEndOfStream {
            pbu: vec!['a'; 8].into_iter().collect::<String>(),
            set_id: 123456,
            end_report_index: 123456789,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = ExecRptEndOfStream::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
