// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct OrderCancel {
    pub biz_id: u32,
    pub biz_pbu: String,
    pub cl_ord_id: String,
    pub security_id: String,
    pub account: String,
    pub owner_type: u8,
    pub side: String,
    pub orig_cl_ord_id: String,
    pub transact_time: u64,
    pub branch_id: String,
    pub user_info: String,
}

impl BinaryCodec for OrderCancel {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u32(self.biz_id);
        put_char_array(buf, &self.biz_pbu, 8);
        put_char_array(buf, &self.cl_ord_id, 10);
        put_char_array(buf, &self.security_id, 12);
        put_char_array(buf, &self.account, 13);
        buf.put_u8(self.owner_type);
        put_char_array(buf, &self.side, 1);
        put_char_array(buf, &self.orig_cl_ord_id, 10);
        buf.put_u64(self.transact_time);
        put_char_array(buf, &self.branch_id, 8);
        put_char_array(buf, &self.user_info, 32);
    }

    fn decode(buf: &mut Bytes) -> Option<OrderCancel> {
        let biz_id = buf.get_u32();
        let biz_pbu = get_char_array(buf, 8)?;
        let cl_ord_id = get_char_array(buf, 10)?;
        let security_id = get_char_array(buf, 12)?;
        let account = get_char_array(buf, 13)?;
        let owner_type = buf.get_u8();
        let side = get_char_array(buf, 1)?;
        let orig_cl_ord_id = get_char_array(buf, 10)?;
        let transact_time = buf.get_u64();
        let branch_id = get_char_array(buf, 8)?;
        let user_info = get_char_array(buf, 32)?;
        Some(Self {
            biz_id,
            biz_pbu,
            cl_ord_id,
            security_id,
            account,
            owner_type,
            side,
            orig_cl_ord_id,
            transact_time,
            branch_id,
            user_info,
        })
    }
}

#[cfg(test)]
mod order_cancel_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_order_cancel_codec() {
        let original = OrderCancel {
            biz_id: 123456,
            biz_pbu: vec!['a'; 8].into_iter().collect::<String>(),
            cl_ord_id: vec!['a'; 10].into_iter().collect::<String>(),
            security_id: vec!['a'; 12].into_iter().collect::<String>(),
            account: vec!['a'; 13].into_iter().collect::<String>(),
            owner_type: 42,
            side: vec!['a'; 1].into_iter().collect::<String>(),
            orig_cl_ord_id: vec!['a'; 10].into_iter().collect::<String>(),
            transact_time: 123456789,
            branch_id: vec!['a'; 8].into_iter().collect::<String>(),
            user_info: vec!['a'; 32].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = OrderCancel::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
