// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use byteorder::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

use crate::cancel_reject::*;
use crate::confirm::*;
use crate::exec_rpt_end_of_stream::*;
use crate::exec_rpt_info::*;
use crate::exec_rpt_sync::*;
use crate::exec_rpt_sync_rsp::*;
use crate::heartbeat::*;
use crate::logon::*;
use crate::logout::*;
use crate::new_order_single::*;
use crate::order_cancel::*;
use crate::order_reject::*;
use crate::platform_state::*;
use crate::report::*;

#[derive(Debug, Clone, PartialEq)]
pub enum SseBinaryBodyEnum {
    Heartbeat(Heartbeat),
    Logon(Logon),
    Logout(Logout),
    NewOrderSingle(NewOrderSingle),
    OrderCancel(OrderCancel),
    Confirm(Confirm),
    CancelReject(CancelReject),
    Report(Report),
    OrderReject(OrderReject),
    PlatformState(PlatformState),
    ExecRptInfo(ExecRptInfo),
    ExecRptSync(ExecRptSync),
    ExecRptSyncRsp(ExecRptSyncRsp),
    ExecRptEndOfStream(ExecRptEndOfStream),
}

#[derive(Debug, Clone, PartialEq)]
pub struct SseBinary {
    pub msg_type: u32,
    pub msg_seq_num: u64,
    pub msg_body_len: u32,
    pub body: SseBinaryBodyEnum,
    pub checksum: u32,
}

impl BinaryCodec for SseBinary {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u32(self.msg_type);
        buf.put_u64(self.msg_seq_num);
        let msg_body_len_pos = buf.len();
        buf.put_u32(0);

        let body_start = buf.len();
        match &self.body {
            SseBinaryBodyEnum::Heartbeat(msg) => msg.encode(buf),
            SseBinaryBodyEnum::Logon(msg) => msg.encode(buf),
            SseBinaryBodyEnum::Logout(msg) => msg.encode(buf),
            SseBinaryBodyEnum::NewOrderSingle(msg) => msg.encode(buf),
            SseBinaryBodyEnum::OrderCancel(msg) => msg.encode(buf),
            SseBinaryBodyEnum::Confirm(msg) => msg.encode(buf),
            SseBinaryBodyEnum::CancelReject(msg) => msg.encode(buf),
            SseBinaryBodyEnum::Report(msg) => msg.encode(buf),
            SseBinaryBodyEnum::OrderReject(msg) => msg.encode(buf),
            SseBinaryBodyEnum::PlatformState(msg) => msg.encode(buf),
            SseBinaryBodyEnum::ExecRptInfo(msg) => msg.encode(buf),
            SseBinaryBodyEnum::ExecRptSync(msg) => msg.encode(buf),
            SseBinaryBodyEnum::ExecRptSyncRsp(msg) => msg.encode(buf),
            SseBinaryBodyEnum::ExecRptEndOfStream(msg) => msg.encode(buf),
        }
        let body_end = buf.len();
        BigEndian::write_u32(
            &mut buf[msg_body_len_pos..msg_body_len_pos + 4],
            (body_end - body_start) as u32,
        );

        let val = CHECKSUM_SERVICE_CONTEXT
            .get("SSE_BIN")
            .and_then(|service| match service.calc(buf) {
                Checksum::U32(v) => Some(v),
                _ => None,
            })
            .unwrap_or(self.checksum);
        buf.put_u32(val);
    }

    fn decode(buf: &mut Bytes) -> Option<SseBinary> {
        let msg_type = buf.get_u32();
        let msg_seq_num = buf.get_u64();
        let msg_body_len = buf.get_u32();
        let body = match msg_type {
            33 => SseBinaryBodyEnum::Heartbeat(Heartbeat::decode(buf)?),
            40 => SseBinaryBodyEnum::Logon(Logon::decode(buf)?),
            41 => SseBinaryBodyEnum::Logout(Logout::decode(buf)?),
            58 => SseBinaryBodyEnum::NewOrderSingle(NewOrderSingle::decode(buf)?),
            61 => SseBinaryBodyEnum::OrderCancel(OrderCancel::decode(buf)?),
            32 => SseBinaryBodyEnum::Confirm(Confirm::decode(buf)?),
            59 => SseBinaryBodyEnum::CancelReject(CancelReject::decode(buf)?),
            103 => SseBinaryBodyEnum::Report(Report::decode(buf)?),
            204 => SseBinaryBodyEnum::OrderReject(OrderReject::decode(buf)?),
            209 => SseBinaryBodyEnum::PlatformState(PlatformState::decode(buf)?),
            208 => SseBinaryBodyEnum::ExecRptInfo(ExecRptInfo::decode(buf)?),
            206 => SseBinaryBodyEnum::ExecRptSync(ExecRptSync::decode(buf)?),
            207 => SseBinaryBodyEnum::ExecRptSyncRsp(ExecRptSyncRsp::decode(buf)?),
            210 => SseBinaryBodyEnum::ExecRptEndOfStream(ExecRptEndOfStream::decode(buf)?),
            _ => return None,
        };
        let checksum = buf.get_u32();
        Some(Self {
            msg_type,
            msg_seq_num,
            msg_body_len,
            body,
            checksum,
        })
    }
}

#[cfg(test)]
mod sse_binary_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_sse_binary_codec() {
        let mut original = SseBinary {
            msg_seq_num: 123456789,
            msg_body_len: 0,
            msg_type: 33,
            body: SseBinaryBodyEnum::Heartbeat(Heartbeat {}),
            checksum: 123456,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = SseBinary::decode(&mut bytes).unwrap();
        original.msg_body_len = decoded.msg_body_len;
        original.checksum = decoded.checksum;
        assert_eq!(original, decoded);
    }
}
